server:
  port: 8080

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/markhakansson
    username: markhakansson
    password: insecurepassword

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always